name: janus

services:
  janus-api:
    image: ${IMAGE_TAG:-janus-api:latest}
    container_name: janus-api
    restart: "no"
    environment:
      JANUS_API_BIND: "0.0.0.0:${INTERNAL_PORT:-8005}"
    expose:
      - "${INTERNAL_PORT:-8005}"
    ports:
      - target: ${INTERNAL_PORT:-8005}
        published: ${PUBLISH_PORT-8005}
        protocol: tcp
    networks:
      - app_net

networks:
  app_net:
    name: ${DOCKER_NETWORK:-janus-net}
    external: true